In [4]:
import numpy as np

In [34]:
#create vector as row
vector_row = np.array([1,2,3,4,5,6,7])

In [35]:
print(vector_row)

[1 2 3 4 5 6 7]


In [36]:
#create vextor as column
vector_column = np.array([[1],
                         [2],
                         [3]])

In [37]:
print(vector_column)

[[1]
 [2]
 [3]]


In [54]:
#create matrix
matrx = np.array([[1,1],
                  [1,2],
                  [1,3],
                  [1,4],
                  [1,5],
                  [1,6],])

In [55]:
print(matrx)

[[1 1]
 [1 2]
 [1 3]
 [1 4]
 [1 5]
 [1 6]]


In [56]:
#create matrix using mat function in np
matrix = np.mat([[1,1],
                  [1,2],
                  [1,3]])

In [57]:
print(matrix)

[[1 1]
 [1 2]
 [1 3]]


In [58]:
#Create Sparse matrix
from scipy import sparse


In [59]:
#Create  matrix
matrix = np.array([[0,0],
                  [1,2],
                  [1,3]])

In [60]:
#Create compress sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [61]:
print(matrix_sparse)

  (1, 0)	1
  (1, 1)	2
  (2, 0)	1
  (2, 1)	3


In [62]:
#Select elements
vector_row[1]

2

In [63]:
vector_column[2]

array([3])

In [64]:
matrx[2]

array([1, 3])

In [65]:
#select all elements of a vector
vector_row[:]

array([1, 2, 3, 4, 5, 6, 7])

In [66]:
#select everything up to and including second element
vector_row[:2]

array([1, 2])

In [67]:
#select everything after second element
vector_row[2:]

array([3, 4, 5, 6, 7])

In [68]:
#select last element
vector_row[-1]

7

In [69]:
#select first two rows and all columns of a matrix
matrx[:2,:]

array([[1, 1],
       [1, 2]])

In [70]:
#select all rows and second column of a matrix
matrx[:,1:2]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [75]:
#create matrix
matrix = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])

In [76]:
#view number of rows and columns
matrix.shape

(3, 4)

In [77]:
#view the  number of elements (rows*columns)
matrix.size

12

In [78]:
#view number of dimensions
matrix.ndim

2

In [79]:
#create a new matrix
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [81]:
#create a function which adds 100 to something
add_100 = lambda i: i+100

In [82]:
#create a vectorized function
vectorized_add_100 = np.vectorize(add_100)

In [83]:
#Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [84]:
#find max value in matrix
np.max(matrix)

9

In [85]:
#find max value in matrix
np.min(matrix)

1

In [86]:
#find max value in vector
np.max(vector_row)

7

In [87]:
#find min value in vector
np.min(vector_row)

1

In [88]:
#find max value in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [89]:
#find max value in each row
np.max(matrix, axis=1)

array([3, 6, 9])

In [90]:
#Return mean
np.mean(matrix)

5.0

In [91]:
#Return variance
np.var(matrix)

6.666666666666667

In [92]:
#Return standard deviation
np.std(matrix)

2.581988897471611

# Reshaping Arrays

In [93]:
#Create 4x3 matrix
matrix= np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]])

In [99]:
#Reshape into 2x6 matrix
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [100]:
#Reshape into 1x-1 matrix. -1 means "as many as needed"
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [101]:
#Reshape into 12 matrix
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Transposing a Vector or Matrix

In [102]:
#create a matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [104]:
#Transpose matrix - cloumns to rows change
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [106]:
#Tranpose row vector
np.array([[1,2,3,4,5,6,7,8]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [107]:
#Tranpose vector
np.array([1,2,3,4,5,6,7,8]).T

array([1, 2, 3, 4, 5, 6, 7, 8])

# Flattening Matrix

In [108]:
#Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
#Flatten matrix
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Finding the Rank of a Matrix

In [110]:
np.linalg.matrix_rank(matrix)

2

# Calculating Determinant

In [115]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

In [116]:
np.linalg.det(matrix)

0.0

# Getting the Diagonal of a Matrix

In [117]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [118]:
#Return diagonal of a matrix
matrix.diagonal()

array([1, 5, 9])